name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Срабатывает при пуше тега, соответствующего шаблону версий, например v1.0.0

      
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-build
        path: build/

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools"

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: build/

  create-release:
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-windows]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Ubuntu build
      uses: actions/download-artifact@v2
      with:
        name: ubuntu-build
        path: ./ubuntu

    - name: Download Windows build
      uses: actions/download-artifact@v2
      with:
        name: windows-build
        path: ./windows

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ubuntu
        asset_name: ubuntu-build.tar.gz
        asset_content_type: application/gzip

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./windows
        asset_name: windows-build.zip
        asset_content_type: application/zip
